version: "3.9"

services:
  military-unit:
    image: military-unit:1
    container_name: military-unit
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:3000"
