version: "3.9"

services:
  military-unit:
    image: military-unit:1
    container_name: military-unit
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - military-unit
